[tool.poetry]
name = "aoc"
version = "0.1.0"
description = ""
authors = ["adi.causevic <adi.causevic@distran.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
advent-of-code-data = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
